CREATE DATABASE HOSPITAL_PATIENT_MANAGEMENT
USE HOSPITAL_PATIENT_MANAGEMENT;

CREATE TABLE ADMIN(
ADMIN_ID INT NOT NULL PRIMARY KEY IDENTITY(1,1),
ADMIN_NAME VARCHAR(50),
ADMIN_POST VARCHAR(30));

CREATE TABLE DEPARTMENT(
DEPARTMENT_ID INT NOT NULL PRIMARY KEY IDENTITY(1,1),
ADMIN_ID INT,
DEPARTMENT_NAME VARCHAR(30),
DEPARTMENT_MANAGER VARCHAR(50)
CONSTRAINT fk_d_adminid FOREIGN KEY(ADMIN_ID) REFERENCES ADMIN(ADMIN_ID)
);

CREATE TABLE OFFICE(
OFFICE_ID INT NOT NULL PRIMARY KEY IDENTITY(1,1),
BUILDING_LOCATION VARCHAR(50),
ROOM_NO INT,
[FLOOR] INT);

CREATE TABLE DOCTOR(
DOCTOR_ID INT NOT NULL PRIMARY KEY IDENTITY(1,1),
DEPARTMENT_ID INT,
OFFICE_ID INT,
FIRST_NAME VARCHAR(50),
LAST_NAME VARCHAR(50),
SPECIALIST VARCHAR(40),
PHONE VARCHAR(14),
EMAIL VARCHAR(30)
CONSTRAINT fk_d_deptid FOREIGN KEY(DEPARTMENT_ID) REFERENCES DEPARTMENT(DEPARTMENT_ID),
CONSTRAINT fk_d_offid FOREIGN KEY(OFFICE_ID) REFERENCES OFFICE(OFFICE_ID)
);

CREATE TABLE PATIENT(
PATIENT_ID INT NOT NULL PRIMARY KEY IDENTITY(1,1), 
FIRST_NAME VARCHAR(50),
LAST_NAME VARCHAR(50),
NATIONALITY VARCHAR(20),
GENDER VARCHAR(14),
ADDRESS VARCHAR(60),
DOB DATE,
PHONE VARCHAR(14),
EMAIL VARCHAR(30)
);

CREATE TABLE APPOINTMENT(
APPOINTMENT_ID INT NOT NULL PRIMARY KEY IDENTITY(1,1),
PATIENT_ID INT,
DOCTOR_ID INT,
[TYPE] VARCHAR(40),
CREATED_DATE DATETIME,
APPOINTMENT_DATE DATE,
APPOINTMENT_TIME TIME,
APPOINTMENT_DESCRIPTION VARCHAR(50)
CONSTRAINT fk_a_patid FOREIGN KEY (PATIENT_ID) REFERENCES PATIENT(PATIENT_ID),
CONSTRAINT fk_a_docid FOREIGN KEY (DOCTOR_ID) REFERENCES DOCTOR(DOCTOR_ID)
);

CREATE TABLE VISIT(
VISIT_ID INT NOT NULL PRIMARY KEY IDENTITY(1,1),
PATIENT_ID INT,
DOCTOR_ID INT,
VISIT_DATE DATE,
DIAGNOSIS VARCHAR(50),
REFERENCE VARCHAR(40)
CONSTRAINT fk_v_patid FOREIGN KEY (PATIENT_ID) REFERENCES PATIENT(PATIENT_ID),
CONSTRAINT fk_v_docid FOREIGN KEY (DOCTOR_ID) REFERENCES DOCTOR(DOCTOR_ID)
);

CREATE TABLE MEDICINE(
MEDICINE_ID INT NOT NULL PRIMARY KEY IDENTITY(1,1),
MEDICINE_NAME VARCHAR(40),
MEDICINE_TYPE VARCHAR(40),
MEDICINE_DESC VARCHAR(60),
MEDICINE_PRICE DECIMAL(5,2)
);

CREATE TABLE PRESCRIPTION(
PRESCRIPTION_ID INT NOT NULL PRIMARY KEY IDENTITY(1,1),
MEDICINE_ID INT,
VISIT_ID INT,
TIMEFRAME VARCHAR(20),
QUANTITY INT,
DOSAGE INT
CONSTRAINT fk_p_medid FOREIGN KEY (MEDICINE_ID) REFERENCES MEDICINE(MEDICINE_ID),
CONSTRAINT fk_p_visitid FOREIGN KEY(VISIT_ID) REFERENCES VISIT(VISIT_ID)
);

CREATE TABLE BILL(
BILLING_ID INT NOT NULL PRIMARY KEY IDENTITY(1,1),
VISIT_ID INT,
DOCTOR_CHARGE DECIMAL(5,2),
MEDICINE_CHARGE DECIMAL(5,2),
LAB_CHARGE DECIMAL(5,2)
CONSTRAINT fk_b_visitid FOREIGN KEY (VISIT_ID) REFERENCES VISIT(VISIT_ID)
);

CREATE TABLE INSURANCE(
INSURANCE_ID INT NOT NULL PRIMARY KEY IDENTITY(1,1),
PATIENT_ID INT,
PUBLISH_DATE DATE,
EXPIRATION_DATE DATE,
INSURANCE_COMPANY VARCHAR(30),
INSURANCE_PLAN_ID VARCHAR(30)
CONSTRAINT fk_i_patid FOREIGN KEY (INSURANCE_ID) REFERENCES PATIENT(PATIENT_ID)
);