/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author harish
 */
public class DoctorModify extends javax.swing.JPanel {

    /**
     * Creates new form PatientCreate
     */
    public DoctorModify() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtPhone = new javax.swing.JTextField();
        txtFirstName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtLastName = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        txtDepartmentID = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtOfficeID = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtSpecialist = new javax.swing.JTextField();
        txtDoctorCode = new javax.swing.JTextField();

        jButton1.setText("Update");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Delete");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("View");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel7.setText("Phone");

        jLabel2.setText("First Name");

        jLabel3.setText("Last Name");

        jLabel9.setText("Email");

        jLabel4.setText("Department ID");

        jLabel5.setText("Office ID");

        jLabel6.setText("Specialist");

        jLabel1.setText("Doctor Code");

        txtDoctorCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDoctorCodeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(50, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(58, 58, 58)
                                .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(58, 58, 58)
                                .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(58, 58, 58)
                                .addComponent(txtSpecialist, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(58, 58, 58)
                                .addComponent(txtOfficeID, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(58, 58, 58)
                                .addComponent(txtDepartmentID, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(58, 58, 58)
                                .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(58, 58, 58)
                                .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(58, 58, 58)
                                .addComponent(txtDoctorCode, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(39, 39, 39)
                        .addComponent(jButton3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton3)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtDoctorCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtDepartmentID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtOfficeID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtSpecialist, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        String connectionUrl = "jdbc:sqlserver://localhost:1433;databaseName=HOSPITAL_PATIENT_MANAGEMENT;encrypt=false;user=sa;password=Practice@123;";
        System.out.println("Connected");
        try
            {
                // call methods that might throw SQLException
//                DriverManager.getDriver("jdbc:sqlserver:");
                
                Connection con = DriverManager.getConnection(connectionUrl);
                Statement stmt=con.createStatement();
                String query = "select * from DOCTOR WHERE DOCTOR_CODE=" + "'"+ txtDoctorCode.getText() + "'";
                System.out.println(query);
                ResultSet rs=stmt.executeQuery(query);
                if(rs.getFetchSize()==0){
                    JOptionPane.showMessageDialog(this, "Patient not found");
                }
                while(rs.next()){
                    txtDepartmentID.setText(rs.getString("DEPARTMENT_ID"));
                    txtOfficeID.setText(rs.getString("OFFICE_ID"));
                    txtEmail.setText(rs.getString("EMAIL"));
                    txtFirstName.setText(rs.getString("FIRST_NAME"));
                    txtLastName.setText(rs.getString("LAST_NAME"));
                    txtSpecialist.setText(rs.getString("SPECIALIST"));
                    txtPhone.setText(rs.getString("PHONE"));
                    break;
                }
                 
                con.close();  
            }
        catch (SQLException e)
            {
                JOptionPane.showMessageDialog(this, "Unable to fetch Patient details, please check the patient code and try again");
                // do something appropriate with the exception, *at least*:
                e.printStackTrace();
            }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String connectionUrl = "jdbc:sqlserver://localhost:1433;databaseName=HOSPITAL_PATIENT_MANAGEMENT;encrypt=false;user=sa;password=Practice@123;";
        System.out.println("Connected");
        try
            {
                // call methods that might throw SQLException
//                DriverManager.getDriver("jdbc:sqlserver:");
                
                Connection con = DriverManager.getConnection(connectionUrl);
                
                String query = " UPDATE DOCTOR SET DOCTOR_CODE=?,FIRST_NAME=?,LAST_NAME=?,DEPARTMENT_ID=?,OFFICE_ID=?,SPECIALIST=?,PHONE=?,EMAIL=? WHERE DOCTOR_CODE=?";

                // create the mysql insert preparedstatement
                PreparedStatement preparedStmt = con.prepareStatement(query);
                preparedStmt.setString (1, txtDoctorCode.getText());
                preparedStmt.setString (2, txtFirstName.getText());
                preparedStmt.setString(3, txtLastName.getText());
                preparedStmt.setString(4, txtDepartmentID.getText());
                preparedStmt.setString(5, txtOfficeID.getText());
                preparedStmt.setString(6, txtSpecialist.getText());
                preparedStmt.setString(7, txtPhone.getText());
                preparedStmt.setString(8, txtEmail.getText());
                preparedStmt.setString(9, txtDoctorCode.getText());

                System.out.println(query);
                preparedStmt.execute();
                
                 
                con.close();
                JOptionPane.showMessageDialog(this, "Patient details updated successfully");
            }
        catch (SQLException e)
            {
                // do something appropriate with the exception, *at least*:
                JOptionPane.showMessageDialog(this, "Unable to delete Patient details, please check the values and try again");
                e.printStackTrace();
            }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String connectionUrl = "jdbc:sqlserver://localhost:1433;databaseName=HOSPITAL_PATIENT_MANAGEMENT;encrypt=false;user=sa;password=Practice@123;";
        System.out.println("Connected");
        try
            {
                // call methods that might throw SQLException
//                DriverManager.getDriver("jdbc:sqlserver:");
                
                Connection con = DriverManager.getConnection(connectionUrl);
                Statement stmt=con.createStatement();
                String query = "DELETE FROM DOCTOR WHERE DOCTOR_CODE=" + "'"+ txtDoctorCode.getText() + "'";
               
                stmt.execute(query);
                
                 
                con.close();
                txtDoctorCode.setText("");
                txtSpecialist.setText("");
                txtDepartmentID.setText("");
                txtEmail.setText("");
                txtFirstName.setText("");
                txtLastName.setText("");
                txtPhone.setText("");
                txtOfficeID.setText("");
                JOptionPane.showMessageDialog(this, "Doctor deleted successfully");
            }
        catch (SQLException e)
            {
                // do something appropriate with the exception, *at least*:
                JOptionPane.showMessageDialog(this, "Unable to delete patient please correct the patient code and try again");
                e.printStackTrace();
            }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtDoctorCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDoctorCodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDoctorCodeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtDepartmentID;
    private javax.swing.JTextField txtDoctorCode;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JTextField txtOfficeID;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txtSpecialist;
    // End of variables declaration//GEN-END:variables
}
